Repository SAP/terraform-provider-sap-cloud-identity-services, pull requests merged in 2025-05, with the labels that each got.

#89 chore: Rename Module
  .goreleaser.yml
  go.mod
  internal/cli/apiObjects/groups/groups.go
  internal/cli/apiObjects/schemas/schemas.go
  internal/cli/applications.go
  internal/cli/applications_test.go
  internal/cli/groups.go
  internal/cli/groups_test.go
  internal/cli/schemas.go
  internal/cli/schemas_test.go
  internal/cli/users.go
  internal/cli/users_test.go
  internal/provider/datasource_application.go
  internal/provider/datasource_applications.go
  internal/provider/datasource_group.go
  internal/provider/datasource_groups.go
  internal/provider/datasource_schema.go
  internal/provider/datasource_schemas.go
  internal/provider/datasource_user.go
  internal/provider/datasource_users.go
  internal/provider/provider.go
  internal/provider/resource_application.go
  internal/provider/resource_application_test.go
  internal/provider/resource_group.go
  internal/provider/resource_group_test.go
  internal/provider/resource_schema.go
  internal/provider/resource_schema_test.go
  internal/provider/resource_user.go
  internal/provider/resource_user_test.go
  internal/provider/type_application.go
  internal/provider/type_group.go
  internal/provider/type_schema.go
  internal/provider/type_user.go
  main.go
Labels: internal, ignore-for-release

#93 chore: Fix release action
  .github/workflows/release.yml
Labels: internal, ignore-for-release

#95 chore: Prep release v0.1.0-beta1
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: internal, ignore-for-release

#96 chore: fixes related to documentation
  .github/ISSUE_TEMPLATE/bug_report.yml
  DEVELOPER.md
  README.md
  REUSE.toml
  assets/VSCode_Command_Palette_Reopen.png
  assets/VSCode_Show_Open_Remote_Window.png
  config/provider-config.txt
  docs/data-sources/users.md
  docs/index.md
  examples/data-sources/sci_users/data-source.tf
  examples/provider/provider.tf
  guides/QUICKSTART.md
Labels: documentation, internal, ignore-for-release

#97 chore: prep for release of 0.1.0-beta2
  .github/ISSUE_TEMPLATE/bug_report.yml
  docs/index.md
  examples/provider/provider.tf
Labels: internal, ignore-for-release

#107 chore: add missing badges to README
  README.md
Labels: internal, ignore-for-release

#109 fix: modified address for debugger
  main.go
Labels: bug
