Repository SAP/terraform-provider-sap-cloud-identity-services, pull requests merged in 2025-06, with the labels that each got.

#113 fix: link fix
  guides/QUICKSTART.md
Labels: bug, documentation

#116 fix: handling of custom schemas in users
  internal/provider/resource_user.go
Labels: bug

#118 chore: Add sonar scan
  .github/workflows/test.yml
  sonar-project.properties
Labels: internal, ignore-for-release

#119 chore: Sonar scan fix
  .github/workflows/test.yml
Labels: internal, ignore-for-release

#127 chore: update OpenTofu version
  .devcontainer/default/devcontainer.json
  .devcontainer/withenvfile/devcontainer.json
  .github/workflows/test-opentofu.yml
Labels: internal, ignore-for-release
