Repository SAP/terraform-provider-sap-cloud-identity-services, pull requests merged in 2025-08, with the labels that each got.

#158 fix: parameter id of applications modified to be Computed only
  docs/resources/application.md
  sci/provider/resource_application.go
  sci/provider/resource_application_test.go
Labels: bug

#164 chore: update Terraform test matrix
  .github/workflows/test.yml
Labels: internal, ignore-for-release

#166 chore: include dependencies to release notes
  .github/release.yml
Labels: internal, ignore-for-release

#178 feat: enhanced resource sci_user with a new parameter 'groups'
  docs/data-sources/user.md
  docs/data-sources/users.md
  docs/resources/user.md
  internal/cli/apiObjects/users/users.go
  sci/provider/datasource_user.go
  sci/provider/datasource_user_test.go
  sci/provider/datasource_users.go
  sci/provider/fixtures/datasource_user.yaml
  sci/provider/resource_user.go
  sci/provider/type_user.go
Labels: enhancement

#176 fix: ensure consistency of plan and state value for the parameter 'default_authenticating_idp'
  sci/provider/fixtures/resource_application.yaml
  sci/provider/fixtures/resource_application_updated.yaml
  sci/provider/resource_application.go
  sci/provider/resource_application_test.go
Labels: bug
